# Generated by Django 6.0.2 on 2026-02-24 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regst', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.CharField(max_length=30)),
                ('result', models.TextField(default='Healthy')),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regst.user')),
            ],
        ),
    ]
